### ISSUE TITLE
7.2.5

### ISSUE THREAD

**Issue by blissfire** [Xruptor/xanOrderHalls#1]
Hey there, seems the 7.2.5 patch broke xanOrderHalls completely. I've disabled all addons except xoh and though the Character List tab shows up on the Class Hall Report, the whole tab is blank.

**Comment by Xruptor** [comment]
Sorry for delay but I'm taking a look at all my addons and are updating them one at a time.  I'll take a look at this issue as I update xanOrderHalls for 8.0 Battle for Azeroth.

**Comment by Xruptor** [comment]
Updated for Battle for Azeroth.
